server:
  port: 8085
  servlet:
    context-path: /api
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tayeur_app?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: root
    password:
    hikari:
      maximumPoolSize: 3
      connectionTimeout: 10000
      initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format-sql: true
    show-sql: true

#springdoc:
  #api-docs:
    #path: /api-docs
  #swagger-ui:
    #path: /swagger-ui.html
    #enabled: false
    #disable-swagger-default-url: true
    #authActionsEnabled: false
